// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0srfvBq4Bm1i_Csz2AKGrGL6KAlHcVA',
    appId: '1:342747963499:web:721e489d7c5033017ed12e',
    messagingSenderId: '342747963499',
    projectId: 'localtammoz',
    authDomain: 'localtammoz.firebaseapp.com',
    storageBucket: 'localtammoz.firebasestorage.app',
    measurementId: 'G-P1TTYC50PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAak8mEFzBpGKE431TJsOdrzWOWji2zgzs',
    appId: '1:342747963499:android:aa2541f5f0b86b827ed12e',
    messagingSenderId: '342747963499',
    projectId: 'localtammoz',
    storageBucket: 'localtammoz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaI9RXKMw0a6prYnJlWpzT3xH3HsGvluY',
    appId: '1:342747963499:ios:3a6d5d774a5b053a7ed12e',
    messagingSenderId: '342747963499',
    projectId: 'localtammoz',
    storageBucket: 'localtammoz.firebasestorage.app',
    iosBundleId: 'com.yourcompany.localTammozChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaI9RXKMw0a6prYnJlWpzT3xH3HsGvluY',
    appId: '1:342747963499:ios:3a6d5d774a5b053a7ed12e',
    messagingSenderId: '342747963499',
    projectId: 'localtammoz',
    storageBucket: 'localtammoz.firebasestorage.app',
    iosBundleId: 'com.yourcompany.localTammozChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq0srfvBq4Bm1i_Csz2AKGrGL6KAlHcVA',
    appId: '1:342747963499:web:9074e91b3f3300cb7ed12e',
    messagingSenderId: '342747963499',
    projectId: 'localtammoz',
    authDomain: 'localtammoz.firebaseapp.com',
    storageBucket: 'localtammoz.firebasestorage.app',
    measurementId: 'G-XTVTYG7204',
  );

}